config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'goals#now'
  resources :goals, only: [:index, :new, :create, :destroy] do
    patch 'pend', to: 'goals#pend'
    patch 'give_up', to: 'goals#give_up'
    resources :stages do
      resources :todos, only: [:index, :create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/common_module.rb
module CommonModule
  extend ActiveSupport::Concern

  #呼び出しインスタンスがGoalの場合とStageの場合で条件分岐
  #Rubyでは整数同士の除算で出る小数は切り捨てられるため、float型へ変換して計算
  def progress_rate
    if self.instance_of?(Goal)
      return nil if self.stages.count == 0
      rate = self.stages.where(status: true).count / self.stages.count.to_f
    else
      return nil if self.todos.count == 0
      rate = self.todos.where(status: true).count / self.todos.count.to_f
    end
    (rate*100).to_i.round
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  include CommonModule
  enum status: { active: 0, pending: 1, done: 2, fail: 3 }
  validates :title, presence: true

  has_many :stages, dependent: :destroy
end

app/models/stage.rb
class Stage < ApplicationRecord
  include CommonModule
  belongs_to :goal
  has_many :todos, dependent: :delete_all
  validates :title, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :stage
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :goals
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.where(user_id: current_user.id)
  end

  def new
    @goal = Goal.new
  end

  def create
    goal = current_user.goals.new(goal_params)
    if goal.save
      redirect_to new_goal_stage_path(goal_id: goal.id)
    else
      render :new
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    redirect_to goals_path, alert: "不正なリクエストです" if goal.user_id != current_user.id
    
    if goal.destroy
      redirect_to goals_path, alert: "#{goal.title}を削除しました"
    else
      redirect_to goals_path, alert: goals.errors.full_messages
    end
  end

  def now
    @goal = current_user.goals.find_by(status: 0)
    @stage = nil
    @todos = nil

    if @goal.present?
      @stage = @goal.stages.where(status: false).first
    end
    
    if @stage.present? && @stage.todos.present?
      @todos = @stage.todos
    end
  end

  def pend
    goal = Goal.find(params[:goal_id])
    if goal.update(status: 1)
      redirect_to root_path, notice: "#{goal.title}を保留しました"
    else
      redirect_to root_path, alert: 'エラー：正しく処理されませんでした'
    end
  end

  def give_up
    goal = Goal.find(params[:goal_id])
    if goal.update(status: 3)
      redirect_to root_path, alert: "#{goal.title}を諦めました"
    else
      redirect_to root_path,  alert: 'エラー：正しく処理されませんでした'
    end
  end

  private
    def goal_params
      params.require(:goal).permit(:title, :detail, :start, :end)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  def index
    @goal = Goal.find(params[:goal_id])
    @stages = Stage.where(goal_id: params[:goal_id])
  end

  def new
    @goal = Goal.find(params[:goal_id])
    @stage = Stage.new
  end

  def create
    @goal = Goal.find(params[:goal_id])
    @stage = Stage.new(stage_params)
    if @stage.save
      redirect_to goal_stages_path(@goal),notice: 'ステージを登録しました。'
    else
      flash.now[:notice] = "エラーが発生しました。もう一度入力してください。"
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:goal_id])
    @stage = Stage.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:goal_id])
    @stage = Stage.find(params[:id])
    if @stage.update(stage_params)
      redirect_to goal_stages_path(@goal),notice: 'ステージを登録しました。'
    else
      render :edit, notice: 'エラーが発生しました。もう一度入力してください。'
    end
  end

  def destroy
    @goal = Goal.find(params[:goal_id])
    stage = Stage.find(params[:id])
    stage.destroy
    redirect_to goal_stages_path(@goal),notice: 'ステージを削除しました。'
  end

  private
  def stage_params
    params.require(:stage).permit(:title, :detail, :start, :end).merge(goal_id: params[:goal_id])
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  protect_from_forgery
  def index
    @goal  = Goal.find(params[:goal_id])
    @stage = @goal.stages.find(params[:stage_id])
    @todo  = @stage.todos.new

    @active_todos = Todo.where(stage_id: @stage.id, status: false)
    @done_todos   = Todo.where(stage_id: @stage.id, status: true)
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to goal_stage_todos_path, notice: "新規Todoを作成しました"
    else
      render :index
    end
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    render json: @todo
  end

  def destroy
    Todo.destroy(params[:id])
    redirect_to goal_stage_todos_path, notice: "Todoを削除しました"
  end

  private
  def todo_params
    params.require(:todo).permit(:title, :status).merge(stage_id: params[:stage_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.haml
.background{style: "background-image: url(#{image_path "moon.jpg"}); background-size: cover; background-attachment: fixed; width: 100vw; height: calc(100vh - 60px)"}
  .container
    .h1.text-center.pt-4{style: 'font-size: 32px; color: white'}
      目標一覧
    - if @goals.blank?
      %hr/
      .text-center
        目標はまだありません
    - else
      %table.table{style: 'color: white'}
        %thead
          %tr
            %th{scope:"col"}
              ＃
            %th{scope:"col"}
              title
            %th{scope:"col"}
              start
            %th{scope:"col"}
              end
            %th{scope:"col"}
              status
            %th{scope:"col"}
              delete
        %tbody
          - @goals.each_with_index do |goal, i|
            %tr
              %td
                = i+1
              %td
                = goal.title
              %td
                = goal.start
              %td
                = goal.end
              %td
                = goal.status_i18n
              %td
                = link_to goal_path(goal), class: "btn btn-outline-danger", data: {confirm: "本当に「#{goal.title}」を削除しますか？"}, method: :delete do
                  削除
            %br/

app/views/goals/new.html.haml
.container.position-relative{style: 'width:60%; margin-top: 40px'}
  = form_with model: @goal do |f|
    .form-group
      = f.label :title, "目標"
      = f.text_field :title, class: "form-control"
    .form-group
      = f.label :detail, "詳細"
      = f.text_area :detail, class: "form-control", rows: "3"
    .d-flex.justify-content-end
      .form-group{{style: 'width:30%'}}
        = f.label :start, "開始日"
        = f.date_select :start, {}, class: "form-control"
      .form-group{style: 'width:30%; margin-left: 20px'}
        = f.label :end, "終了目標日"
        = f.date_select :end, {}, class: "form-control"
    = f.submit "作成", class: "btn btn-dark position-absolute", style: 'right:20px'

app/views/goals/now.html.haml
.background{style: "background-image: url(#{image_path "moon.jpg"}); background-size: cover; background-attachment: fixed; width: 100vw; height: calc(100vh - 60px)"}
  .container.text-center{style: 'color: white'}
    .row
      .col-2.mt-5
        = current_user.name
        =link_to goals_path, class:  "btn btn-outline-secondary btn-lg btn-block mt-2", style: 'color: white; border-color: white' do
          目標一覧
        - unless @stage.blank?
          =link_to goal_stages_path(goal_id: @goal.id), class:  "btn btn-outline-secondary btn-lg btn-block mt-2", style: 'color: white; border-color: white' do
            ロードマップ
          =link_to goal_stage_todos_path(goal_id: @goal.id, stage_id: @stage.id),
            class:  "btn btn-outline-secondary btn-lg btn-block mt-2", style: 'color: white; border-color: white' do
            Todo
      .col.border-left.mt-3
        - if @goal.blank?
          = link_to new_goal_path, style: 'text-decoration: none;' do
            .btn.btn-outline-primary.btn-lg.btn-block{style: 'margin-top:60px; border: 1px solid white'}
              .goal{style: 'font-size: 32px; color: white'} 新しい目標を設定する
        - else
          %hr/
          .row.justify-content-center
            .h2.col-md-3
              現在の目標：
            .h2.col-md-7
              = @goal.title
            .col-md-2
              達成目標日：
              %br/
              = @goal.end
          %hr/
          - if @stage.blank?
            = link_to new_goal_stage_path(goal_id: @goal.id), class: "btn btn-outline-primary", style: 'padding: 20px 200px; border: 1px solid white' do
              .h3{style: 'color: white'} ロードマップを描く
            %hr/
          - else
            .row.justify-content-center
              .h3.col-md-3
                期間目標：
              .h3.col-md-7
                = @stage.title
              .col-md-2
                達成目標日：
                %br/
                = @stage.end
            %hr/
            - if @todos.blank?
              = link_to goal_stage_todos_path(goal_id: @goal.id, stage_id: @stage.id),
                 class: "btn btn-outline-primary", style: 'padding: 20px 200px;  border: 1px solid white' do
                .h3{style: 'color: white;'} Todoリストの作成
              %hr/
            - else 
              .mb-3
                ここにTodoリストを表示するよ
                %br/
                = @todos
          .d-flex.justify-content-center
            = button_to '保留する', goal_pend_path(goal_id: @goal.id), method: :patch, class: "btn btn-outline-info", data: {confirm: "目標を保留します"},
              style: 'color: white; border-color: white'
            = button_to '諦める', goal_give_up_path(goal_id: @goal.id), method: :patch, class: "btn btn-outline-danger", data: {confirm: "本当に諦めますか？"}, style: 'margin-left: 10px;',
              style: 'color: white; border-color: white'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ObjetivoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .d-flex.justify-content-between
        = link_to root_path,style:" padding-left: 20px; text-decoration: none; color: white; font-size: 40px; " do
          OBJETIVO
        - if user_signed_in?
          .header-right-box{style: 'padding: 10px;' }
            = link_to edit_user_registration_path do
              %button.btn.btn-outline-light
                設定
            = link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} do
              %button.btn.btn-outline-light
                ログアウト
        - else
          .header-right-box{style: 'padding: 10px;' }
            = link_to new_user_registration_path do
              %button.btn.btn-outline-light
                新規登録
            = link_to new_user_session_path do
              %button.btn.btn-outline-light
                ログイン
    = render 'layouts/notifications'
    = yield

app/views/stages/edit.html.haml
.stage
  .stage__new
    新規ステージの作成
    .stage__new__info
      = form_with model: [@goal,@stage],local:true do |f|
        = f.text_field :title, class: "stage__new__info__title",placeholder:"新規ステージ名"
        = f.date_select :start, class: "stage__new__info__start"
        = f.date_select :end, class: "stage__new__info__end"
        = f.text_area :detail, class: "stage__new__info__detail",placeholder:"詳細"
        = f.submit "保存する", class: "stage__new__info__send"

app/views/stages/index.html.haml
.stage
  .stage__header
    = link_to goals_path,class:"header__exit badge badge-pill badge-secondary" do
      ゴールに戻る
    .stage__header__goal-name
      ゴール名:
      = @goal.title
    .stage__header__add
      = link_to new_goal_stage_path,class:"header__add badge badge-pill badge-success" do
        ステージの追加
  .stage__main
    .stage__main__stages
      - @stages.each do |stage|
        .stage__main__stages__stage-list
          = link_to edit_goal_stage_path(@goal,stage),id:"edit",class:"stage__main__stages__stage-list__edit badge badge-pill badge-warning" do
            編集
          = link_to goal_stage_path(@goal,stage),method: :delete,id:"delete", class:"stage__main__stages__stage-list__delete badge badge-pill badge-danger" do
            削除
          .stage__main__stages__stage-list__title
            %h3
              ステージ名：
            = stage.title
          .stage__main__stages__stage-list__start
            %h4
              開始日：
              = stage.start
          .stage__main__stages__stage-list__end
            %h4
              終了日：
              = stage.end
          .stage__main__stages__stage-list__detail
            = stage.detail
          .stage__main__stages__stage-list__speed
            .progress
              .progress-bar.progress-bar-striped.bg-danger{role:"progressbar", style:"Width: 25%", "aria-valuemin":"25" ,"aria-valuemax":"100"}
            .stage__main__stages__stage-list__speed__view
              進捗率
              -if stage.progress_rate == nil
                ー
              -else
                = stage.progress_rate
                %div
                  パーセント
          = link_to goal_stage_todos_path(@goal,stage), class:"stage__main__stages__stage-list__tasks" do
            %button.btn.btn-info{type: "button"}
              todoへ
              %span.badge.badge-light
                = stage.todos.count
  .stage__footer

app/views/stages/new.html.haml
.stage
  .stage__new
    新規ステージの作成
    .stage__new__info
      = form_with model: [@goal,@stage],local:true do |f|
        = f.text_field :title, class: "stage__new__info__title",placeholder:"新規ステージ名"
        = f.date_select :start, class: "stage__new__info__start"
        = f.date_select :end, class: "stage__new__info__end"
        = f.text_area :detail, class: "stage__new__info__detail",placeholder:"詳細"
        = f.submit "投稿する", class: "stage__new__info__send"

app/views/todos/_active_todo.html.haml
%li.list-group-item
  %input{class: "todo-check-box", id: "box-#{active_todo.id}", type: "checkbox", data: {todoid: "#{active_todo.id}"}}
  %label{for: "box-#{active_todo.id}"}
  %p
    = active_todo.title
  = link_to "削除", goal_stage_todo_path(@goal,@stage,active_todo), method: "delete"

app/views/todos/_done_todo.html.haml
%li.list-group-item
  %input{class: "todo-check-box", id: "box-#{done_todo.id}", type: "checkbox", checked: "checked", data: {todoid: "#{done_todo.id}"}}
  %label{for: "box-#{done_todo.id}"}
  %p
    = done_todo.title
  = link_to "削除", goal_stage_todo_path(@goal,@stage,done_todo), method: "delete"

app/views/todos/index.html.haml
.todo-index
  .todo-index__stage-info
    .todo-index__stage-info--title
      %p
        = @stage.title
    .todo-index__stage-info--end-date
      %p
        期日
        %br
        = @stage.end
    .todo-index__stage-info--progress-rate
      %p
        進捗率
        = @stage.progress_rate
        \%
  .todo-index__main
    .todo-index__main--todo-active
      %ul.list-group
        = render partial: 'active_todo', collection: @active_todos
    .todo-index__main--todo-done
      %buttun.btn.btn-info 完了済みToDoを表示する
      %ul.list-group
        = render partial: 'done_todo', collection: @done_todos

    .todo-index__main--create-form
      = form_with model: [@goal, @stage, @todo] do |form|
        .form-row.align-items-center
          .col-auto
            = form.text_field :title, class: "form-control mb-2", id: "text5a", placeholder: "新規登録"
            = form.submit "登録", class: "btn btn-info"